trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade pip requests os smtplib datetime
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    repository: 775362094965.dkr.ecr.us-west-2.amazonaws.com/weather-project
    dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: 'latest'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'weather'
    regionName: us-west-2
    imageSource: 'imagename'
    sourceImageName: '775362094965.dkr.ecr.us-west-2.amazonaws.com/weather-project'
    sourceImageTag: 'latest'
    pushTag: 'latest'
    repositoryName: 'weather-project'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'weather'
    regionName: 'us-west-2'
    awsCommand: 'lambda'
    awsSubCommand: 'update-function-code'
    awsArguments: '--function-name weather-updater --image-uri 775362094965.dkr.ecr.us-west-2.amazonaws.com/weather-project:latest'